### ISSUE TITLE
Use of undefined constant CURLOPT_HTTP_VERSION - assumed 'CURLOPT_HTTP_VERSION' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by bologer** [sanchezzzhak/kak-clickhouse#36]
Не удается использовать миграцию из-за следующей ошибки в консоли: 

```
Exception 'yii\base\Exception' with message 'Query error: Use of undefined constant CURLOPT_HTTP_VERSION - assumed 'CURLOPT_HTTP_VERSION' (this will throw an Error in a future version of PHP)'

in /vendor/kak/clickhouse/Command.php:271

Stack trace:
#0 /vendor/yiisoft/yii2/db/Command.php(399): kak\clickhouse\Command->queryInternal('fetchAll', NULL)
#1 /vendor/kak/clickhouse/Schema.php(168): yii\db\Command->queryAll()
#2 /vendor/yiisoft/yii2/db/Schema.php(744): kak\clickhouse\Schema->loadTableSchema('migration')
#3 /vendor/yiisoft/yii2/db/Schema.php(194): yii\db\Schema->getTableMetadata('{{%migration}}', 'schema', true)
#4 /vendor/yiisoft/yii2/console/controllers/MigrateController.php(210): yii\db\Schema->getTableSchema('{{%migration}}', true)
#5 /vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(875): yii\console\controllers\MigrateController->getMigrationHistory(NULL)
#6 /vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->getNewMigrations()
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#8 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('up', Array)
#11 /vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('up', Array)
#12 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#13 /vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/up', Array)
#14 /vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 /yii(23): yii\base\Application->run()
#16 {main}
```

В чем может быть проблема?

**Comment by sanchezzzhak** [comment]
Привет, какая версия PHP `php -v ` и установлено-ли расширение php-curl?
Проверить можно вот так.
```
aptitude search php-curl
```
или универсально 
```
php -m | grep "curl"
```
