### ISSUE TITLE
Обработка {{%table_name}}

### ISSUE THREAD

**Issue by bologer** [sanchezzzhak/kak-clickhouse#37]
Похоже, что не работает обработка таблиц на подобии {{%table_name}}. 

Запуск миграций выдает следующую ошибку: 

```
Yii Migration Tool (based on Yii v2.0.17)

Creating migration history table "migration"...Exception 'yii\db\Exception' with message 'Need set specific settings for engine table'

in /vendor/kak/clickhouse/QueryBuilder.php:159

Stack trace:
#0 /vendor/yiisoft/yii2/db/Command.php(638): kak\clickhouse\QueryBuilder->createTable('{{%migration}}', Array, NULL)
#1 /vendor/yiisoft/yii2/console/controllers/MigrateController.php(271): yii\db\Command->createTable('{{%migration}}', Array)
#2 /vendor/yiisoft/yii2/console/controllers/MigrateController.php(211): yii\console\controllers\MigrateController->createMigrationHistoryTable()
#3 /vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(875): yii\console\controllers\MigrateController->getMigrationHistory(NULL)
#4 /vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->getNewMigrations()
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('up', Array)
#9 /vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('up', Array)
#10 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#11 /vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/up', Array)
#12 /vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /yii(23): yii\base\Application->run()
#14 {main}
```

**Comment by sanchezzzhak** [comment]
Миграции отсутствуют в проекте
Нужно добавлять собственный консольный контролер по обработке миграций + собственный класс Migrate, так-как все зашито на PDO драйвер харкодом в  yii2.
